### ISSUE TITLE
RingFinger does not bend correctly

### ISSUE THREAD

**Issue by BoomRaccoon** [gzmuszynski/UE-to-Rigify#1]
Exported the default quin skeletal mesh from unreal and imported it using the "Send to Unreal" addon.
After importing I used the "UE to rigify" addon with your quinn template to create the rig. From my little testing everything looked quite nice but the ring finger does not bend correctly.

Would love to solve this and get my animations going.

**Comment by gzmuszynski** [comment]
Can you provide screenshots or reproduction steps?

**Comment by gzmuszynski** [comment]
@BoomRaccoon  Please try the updated template and tell me if that fixes the issue

**Comment by BoomRaccoon** [comment]
@gzmuszynski I realized afterwards that the pinky had the same issue.

So I downloaded the new template and the ring finger seems to be fixed but the pinky is now a different kind of weird.
Scaling the control on one side - to make it bend - won't work and **** up the pinky on the other side.

I'd appreciate it if you could share some info on how you fixed it because my ideas didn't work.

**Comment by gzmuszynski** [comment]
@BoomRaccoon I realized sides were mixed up somehow. I double checked, and now it should be alright. If you needed to edit the bone remap yourself, you could edit them by selecting "source to deform" in UE to Rigify toolbar, and then (easiest) make new viewport -> in window type menu select bone remapping nodes, and then select active bone remapping graph.
![image](https://user-images.githubusercontent.com/17852750/212889953-5fb36e04-7a3e-4237-b29a-77aa9b444637.png)

**Comment by BoomRaccoon** [comment]
It works perfectly now.
Thank you for your work

So the issue with the pinky was the remapping but what about the previous issue? The deformation of the fingers was strange because the fingers got squashed, was that also a remapping problem?
I looked at the weight paint but that wasn't the issue and the rotation seemed also fine.

**Comment by gzmuszynski** [comment]
I remapped the sections of the source skeleton fingers to incorrect control skeleton bones: ring 01 to ring metacarpal, ring 02 to ring 01, etc. I can't explain how did that happen, but it was fortunately easy fix
