### ISSUE TITLE
Male Mannequin Rigify Rig doesn't match

### ISSUE THREAD

**Issue by miltoncvxp** [gzmuszynski/UE-to-Rigify#2]
Hi, having an odd issue here, 
After importing the male skm manny (lyra) from UE5 into blender, I choose the armature for source in the UE to Rigify Tookit window.
I choose the Male Mannequin Template, and when I click on Convert, it creates a rigify rig, but the bones are shifted behind the mesh on the y axis slightly, and the arms/hand/leg bones are all off. I've tried using the "manny" present instead, and it is much closer, but the hand/finger bones are offset, some not receiving any weight to the mesh. 
![ue2rigify_issue](https://user-images.githubusercontent.com/132939150/236935024-b6e5d0fc-d111-41bf-8348-578eef9fe890.png)

**Comment by gzmuszynski** [comment]
hi, can you provide some information to help me debug the issue?
- UE-to-Rigify version
- Send-To-Unreal version (I'm assuming that's what was used to import the SKM)
- Blender version
- Unreal version
- Export options used during Unreal's export-to-fbx.
- Would help me much, if you also provided .blend file and .fbx file to compare against

thanks in advance, I'll try to reproduce the issue on my end after I clock out at work

**Comment by miltoncvxp** [comment]
Hello thank you for your response! to answer your questions:
-UE to Rigify version 1.6.1
-I have not used Send-to-Unreal, have imported direct to SK Mannequin, but
will do that next
-I'm using Blender 3.4.1
-Unreal 5.1
I had an issue replying with attachments so tryin google drive instead:
https://drive.google.com/file/d/1KdXkSS9HTdb1ni0h17cigCixYExxEHqU/view?usp=share_link

The big thing is that I can't seem to get either a Male Mannequin or UE4
Manny preset to match with the SKM from UE5.
Aside from that, when I export to UE5, the IK keyframes are static, so when
doing updates to Lyra/Weapon anims, I have to manually constrain and bake
IK bones after going from control back to source to export.
Thank you thank you, appreciate your help a lot!
Best
Milton

**Comment by gzmuszynski** [comment]
thank you for the information. I'll get back to you regarding the issue, once I've located and fixed it. 

In the meantime, regarding other nuances:
- as per Epic's guide using Send-To-Unreal import option to import fbx meshes into blender is recommended, due to fbx importer errors, and that's what we - in the company I work for - use, when working with blender-UE workflow, so that's my big recommendation, because we've encountered plenty of errors when using blender's standard import/export options.
- for IK bones: I have personally not created any animations requiring those. I might be wrong in the assumption, but I think Epic deprecated ik bones either in metahumans, Echo, or Manny and Quinn skeletons. In project at my work we don't use them anyway, we have custom IK setup in animation blueprints. I'll double check if those bones are properly remapped in the templates. 

I'll get to it ASAP with matching software versions.

**Comment by miltoncvxp** [comment]
Thanks so much Grzegorz!
I will definitely try the Send-To-Unreal plugin.
Another thing I noticed, is that the Rigify elements driving the UE
skeleton is what is off specifically. If I do a general animation with
rigify, then convert back to export, I can adjust hand bones (which were
distorted by rigify rig) before exporting FBx.
Not sure where Epic is with depreciating those bones, but my project goals
right now are to replace Lyra animations, and those are specifically wired
to those bones for whatever reason when using rifle/pistol anim layers. Was
hoping to use a tool like this to be able to update a Lyra project for Beta
so that I don't have to rework a weapons anim layer system from scratch.

**Comment by gzmuszynski** [comment]
I have reproduced the issue on my end, when using "Mannequin" template on "Manny" mesh. After loading "Manny" template, the controls have correct placement, but pinky and ring fingers' 01 bones are not deforming. Default importer vs Send-to-Unreal was irrelevant to this case.

Also IK bones were not baking at all.

Fix for those two issues is uploaded (hopefully). there might be some issues with IK baking, when using FK posing (mismatched IK controls transform with actual deformation bone transform. Might need to use IK posing to mitigate that)
Please try the newest Manny template, and let me know if that fixed the issues. If it did, feel free to mark this issue as closed

**Comment by miltoncvxp** [comment]
Thanks so much!
I will redownload the latest blender plugin and the newest manny template
and let you know!

**Comment by miltoncvxp** [comment]
All the IK's are baking now, very helpful!
The only thing I saw is that the middle joint of the ring fingers on both
sides is still distorted. Pinkys are looking good.
thanks for your updates on this man, it's a really great tool

**Comment by gzmuszynski** [comment]
Looking into it

**Comment by gzmuszynski** [comment]
There should be new version of the template available to remedy the issue. Please download and let me know if there are any further issues

**Comment by miltoncvxp** [comment]
Finger fixed, thanks so much, will be sure to mark as resolved!
