### ISSUE TITLE
I want to know how to use it

### ISSUE THREAD

**Issue by vairta** [gzmuszynski/UE-to-Rigify#4]
these templates, how to use it

**Comment by gzmuszynski** [comment]
[https://www.youtube.com/watch?v=eLnZfQRR-DE](https://www.youtube.com/watch?v=eLnZfQRR-DE)

**Comment by vairta** [comment]
Thank you, but the official addon "UE to Rigify" url is 404 ...

**Comment by gzmuszynski** [comment]
I don't provide support for Epic Games' tools. Only for the templates I made. Search the internet, unreal documentation or unreal forums.

**Comment by vairta** [comment]
Thank you very much
